### ISSUE TITLE
null elements on some `FAIL`s

### ISSUE THREAD

**Issue by tute** [GoogleChrome/accessibility-developer-tools#125]
Thanks for your work in this useful library!

We were seeing null elements while working in https://github.com/accesslint/access_lint-js. We tried to isolate the issue, and tried to use the command line you suggest (`phantomjs tools/runner/audit.js http://google.com`) with current master, to audit google.com. Our current phantomjs version is 1.9.8.

We did the following change to the runner to illustrate the issue (namely, show results and elements):

```diff
diff --git a/tools/runner/audit.js b/tools/runner/audit.js
index 9e01b43..1280334 100644
--- a/tools/runner/audit.js
+++ b/tools/runner/audit.js
@@ -32,10 +32,13 @@ if (system.args.length !== 2) {
     } else {
       page.injectJs('../../dist/js/axs_testing.js');
       var report = page.evaluate(function() {
-        var results = axs.Audit.run();
-        return axs.Audit.createReport(results);
+        return axs.Audit.run();
+      });
+      report.map(function(e) {
+        console.log(JSON.stringify(e.result))
+        console.log(JSON.stringify(e.elements))
+        console.log("----------------")
       });
-      console.log(report);
       phantom.exit();
     }
   });
```

This is the result we get:

```
----------------
"FAIL"
[null]
----------------
"PASS"
[]
----------------
"FAIL"
[null,null,null,null,null,null,null,null,null,null,null,null]
----------------
"NA"
undefined
----------------
"FAIL"
[null,null,null,null]
----------------
"NA"
undefined
----------------
"PASS"
[]
----------------
"NA"
undefined
----------------
"NA"
undefined
----------------
```

But we expect to see actual elements, rather than `null`. Why does this happen?

cc @euraldius

**Comment by RickSBrown** [comment]
The documentation for `page.evaluate` states
> **Note**: The arguments and the return value to the evaluate function must be a simple primitive object. The rule of thumb: if it can be serialized via JSON, then it is fine.
**Closures, functions, DOM nodes, etc. will not work!**
> - http://phantomjs.org/api/webpage/method/evaluate.html

I'm pretty sure that's what is affecting us here.

What we could do is return objects that look a lot like the DOM elements but are not the DOM elements themselves. This could be turned on by adding a new config flag to `axs.Audit.run()` (`axs.AuditConfiguration` to be precise). We would then turn this on in the phantomJS runner.

I noticed that returning cloned elements seems to bypass this issue (e.g. `element.cloneNode(true)`).

I'll raise a pull request for this, code speaks louder than words.

@tute I'd be interested to know, would this meet your needs?

**Comment by tute** [comment]
Thanks Rick, it does sound good. I'll test the PR when you are ready.

**Comment by RickSBrown** [comment]
@tute The more I think about this the more I think it might be something best handled by the caller (you) rather than built into the accessibility developer tools.

I've 90% finished writing the code but am not convinced it is something we should be doing. This is ultimately a decision for @alice and I'll wait to hear from her before I actually open the PR.

Here is a modification to your example above that shows one way you could achieve what you want in your demo:

```javascript
var page = require('webpage').create(),
    system = require('system'),
    url;

if (system.args.length !== 2) {
  console.log('Usage: phantomjs audit.js URL');
  phantom.exit();
} else {
  url = system.args[1];
  page.open(url, function (status) {
    if (status !== 'success') {
      console.log('Failed to load the page at ' +
        url +
        ". Status was: " +
        status
        );
      phantom.exit();
    } else {
      page.injectJs('../../dist/js/axs_testing.js');
      var audit = page.evaluate(function() {
        var results = axs.Audit.run();
        var report = axs.Audit.createReport(results);
        results.forEach(function(result) {
            if (result.elements && result.elements.length) {
                result.elements = result.elements.map(function(el) {
                    return el.cloneNode(true);
                });
            }
         });
        return {report: report, results: results};
      });
      audit.results.forEach(function(e) {
        console.log(JSON.stringify(e.result));
        console.log(JSON.stringify(e.elements));
        console.log("----------------");
       });
      console.log(audit.report);
      phantom.exit();
    }
  });
}
```
The main point here is that anything you want to do with the DOM nodes in the audit results you need to do before the page.evaluate call returns.

**Comment by alice** [comment]
I'd be curious to know what you intend to do with the returned nodes - I can't see how a node would be useful outside of the DOM context, but I could well be missing something.

If this has the potential to be useful, perhaps we could add a method alongside `axs.Audit.createReport()` which will clone each of the nodes in each result's `elements` array, but I'd like to understand why this would be useful before we do that.

Otherwise, is there a modification we could make to `createReport()` which would make it more useful for you?

**Comment by tute** [comment]
Thank you @RickSBrown and @alice. We use that script to show in accesslint.com elements of a page that are not accessible and that should be taken care of. With Rick's code we may be able to do it without needing any change in axs. We'll investigate, thank you again.

cc @ckundo @euraldius

**Comment by RickSBrown** [comment]
I think we can close this one now...?
