### ISSUE TITLE
Using the Command Line Runner

### ISSUE THREAD

**Issue by techxplorer** [GoogleChrome/accessibility-developer-tools#274]
Hi,

I'm looking into integrating this tool into my workflow, as it is very valuable. I've noticed and odd behaviour that perhaps needs some documentation. 

The command line runner, when working with a file path, needs that path to end in `.html`. 

For example running the command like this fails:
```
phantomjs /paht/to/tools/runner/audit.js /path/to/input/file/index
```
Will fail with the following error:
```
Failed to load the page at /path/to/input/file/index. Status was: fail
```
However running the command like this works:
```
phantomjs /paht/to/tools/runner/audit.js /path/to/input/file/index.html
```
I'm not sure if this is an issue with the script or with phantomjs. For the record I'm running the following version:

```
$ phantomjs -v
2.1.1
```
With the latest checkout of this repository. 

If having the path end in `.html` is required, can I suggest a more user friendly error message to that effect?

With thanks. 

-Corey

**Comment by jdan** [comment]
Hey @techxplorer,

Thanks for reporting. This error message definitely comes from us (source: https://github.com/GoogleChrome/accessibility-developer-tools/blob/d1c98e88a853bff77ad054e84ae7f18c60d31f48/tools/runner/audit.js#L27-L34). The error message appears because phantomjs is attempting to load a page (`/index`) which does not exist (`/index.html` does, however).

At this point the library will not know if the user left out the file extension, or if they misspelled the filename all together, so sadly I'm not sure how we could provide a more helpful error message here (all we know is that the page couldn't load).

I'm going to close this issue for now, but I'm happy to carry on a conversation or answer any other questions you may have about this! Sorry for the confusion here.
