### ISSUE TITLE
AX_ARIA_13 and AX_TOOLTIP_01 displayed in test results, but not on this Git Wiki.  

### ISSUE THREAD

**Issue by ssjjcc** [GoogleChrome/accessibility-developer-tools#280]
I'm pretty new to Accessibility Testing and was wondering about the audit rules AX_ARIA_13 and AX_TOOLTIP_01. When I run a test on a page, these two audit rules don't appear in the Audit Rules in the Wiki Tab (https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules), nor do they always appear in the Goggle Chrome Plugin Accessibility Audit. 

For example:
![ax_aria_13](https://cloud.githubusercontent.com/assets/19228236/15163716/603aea5a-16c7-11e6-9caa-95c2d145b770.png)

Should I not be seeing these because these rules don't exist or have they just not been added to this page's wiki?

Thanks!

**Comment by jdan** [comment]
Heya @ssjjcc,

Welcome to wild world of accessibility testing :) You're absolutely right, those rules are not present in the wiki. I went ahead and made two stubs just so the links aren't broken - https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules/_compare/b212de272832768d3f88c4058a7238297a81a893...6095fb53952a36245929460b7e576b83d59e696e. Be sure to holler if any other entries are missing from the wiki.

cc'ing @kennyw12 and @ctaymor in case they want to write little blurbs for those audits.

Regarding your second point: the chrome extension was last built and released on October 12, 2015. These plugins appear to have landed after that.

I'll go ahead and close this issue since the links are no longer broken, but be sure to let me know if you come across any other weirdness. Thanks for reporting 🌟

**Comment by ssjjcc** [comment]
Awesome! Glad to have helped and thanks for getting that taken care of.
