### ISSUE TITLE
AX_ARIA_04

### ISSUE THREAD

**Issue by sKopheK** [GoogleChrome/accessibility-developer-tools#332]
Hello, got this warning about invalid ARIA attributes in my markup. What is exactly wrong in this code, e.g.:

`<input autocomplete="false" class="k-password k-input" data-val="true" data-val-regex="Password must be between 6 and 255 characters" data-val-regex-pattern=".{6,255}" data-val-required="'Choose password' should not be empty." id="Password" name="Password" type="password" data-role="password" role="password" aria-valuenow="" aria-disabled="false" aria-readonly="false">`

?

**Comment by ricksbrown** [comment]
I haven't run the tool over it but at a glance:

1. The `role` attribute is [part of ARIA](https://www.w3.org/TR/wai-aria/roles) and the values it can take are limited. There is (currently) no such role as `password`. 

2. Even if `password` did exist you'd still likely get a warning because the native semantics are unambiguous. In other words `<input type="password"` is quite enough to say "this is a password field", the `role="password"` would be redundant. Read [ARIA adds nothing to default semantics of most HTML elements](https://www.w3.org/TR/aria-in-html/#aria-adds-nothing-to-default-semantics-of-most-html-elements) and note:

> In the majority of cases setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and not recommended as these properties are already set by the browser.

3. `aria-valuenow` is [only used](https://www.w3.org/TR/wai-aria/states_and_properties#aria-valuenow) in the roles: `progressbar`, `scrollbar`, `slider`, `spinbutton`

**Comment by sKopheK** [comment]
Thanks for the reply, Rick, I'll use the advices to improve my code.
