### ISSUE TITLE
make assertions on contrast of placeholder text in inputs

### ISSUE THREAD

**Issue by ckundo** [GoogleChrome/accessibility-developer-tools#80]
Placeholder text should meet contrast requirements as well as body text.

**Comment by alice** [comment]
I'm not too sure about this one. I've seen arguments for having placeholder text meet WCAG, but I believe there is also concern that raising the contrast might make it easy to confuse with an actual value rather than a placeholder - e.g. note that the user agent styles for placeholders typically don't meet WCAG colour contrast requirements. I think there's a broader issue about how to style placeholders to make them readable without causing this confusion, but until that is the default I don't think it's fair for us to test for it.
